
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: root
    password: Quarant!ne01
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddlAuto: update
    showSql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: PRODUCT-SERVICE


  config:
    import: configserver:http://localhost:9296

#    application:
#      name: spring-cloud-eureka-client
#  server:
#    port: 0
#  eureka:
#    client:
#      fetchRegistry: true
#      registerWithEureka: true
#      serviceUrl:
#        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#    instance:
#      preferIpAddress: true

