server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb
    username: root
    password: Quarant!ne01
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddlAuto: update
    showSql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: PAYMENT-SERVICE


  config:
    import: configserver:http://localhost:9296
