
server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: Quarant!ne01
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddlAuto: update
    showSql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: ORDER-SERVICE


  config:
    import: configserver:http://localhost:9296


resilience4j:
  circuitBreaker:
    instances:
      external:
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 5

#    spring:
#      application:
#        name: spring-cloud-eureka-client
#    server:
#      port: 0
#    eureka:
#      client:
#        registerWithEureka: true
#        fetchRegistry: true
#        serviceUrl:
#          defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#      instance:
#        preferIpAddress: true


